### PR TITLE
Master merge v3.3

### PR DESCRIPTION
**Pull request by ghost**
merged master of  caseyamcl/phpoaipmh back in + updated git workflow to include php 7.4 and php 8.0

### CODE REVIEW

**Review by olexiyk — APPROVED** [review]

**Comment by olexiyk** [comment]
Code changes look good. I assume there were no conflicts when merging? It looks like the only change was in src/Phpoaipmh/RecordIterator.php. 

Also, it looks like actions didn't run? Can you check why?

**Comment by ghost** [comment]
I merged the other branch into my new separate branch, so that gave conflicts on the points where RG edited the codebase. But that was almost nothing and easily solvable. 

I added PHP8.0 support to the GitHub actions, but apparently the codebase is not ready for that.

**Comment by ghost** [comment]
I removed PHP 8.0 from Github actions for now

**Comment by olexiyk** [comment]
Thanks @DaanRG

**Pull request merged**
